site_name: My Docs

theme:
  name: material
  logo: 'images/logo.png'
  favicon: 'images/favicon.ico'
  palette:
    - scheme: default
      primary: 'blue grey'
      accent: 'purple'
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.tracking
    - navigation.indexes
